In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./02-14-2018.csv")

In [5]:
df.dropna(inplace=True)

In [9]:
df.drop(columns=['Label'])

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,0,0,14/02/2018 08:31:01,112641719,3,0,0,0,0,0,...,0,0,0.0,0.0,0,0,56320859.5,139.300036,56320958,56320761
1,0,0,14/02/2018 08:33:50,112641466,3,0,0,0,0,0,...,0,0,0.0,0.0,0,0,56320733.0,114.551299,56320814,56320652
2,0,0,14/02/2018 08:36:39,112638623,3,0,0,0,0,0,...,0,0,0.0,0.0,0,0,56319311.5,301.934596,56319525,56319098
3,22,6,14/02/2018 08:40:13,6453966,15,10,1239,2273,744,0,...,6,32,0.0,0.0,0,0,0.0,0.000000,0,0
4,22,6,14/02/2018 08:40:23,8804066,14,11,1143,2209,744,0,...,6,32,0.0,0.0,0,0,0.0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,80,6,14/02/2018 10:53:23,10156986,5,5,1089,1923,587,0,...,2,20,0.0,0.0,0,0,0.0,0.000000,0,0
1048571,80,6,14/02/2018 10:53:33,117,2,0,0,0,0,0,...,0,20,0.0,0.0,0,0,0.0,0.000000,0,0
1048572,80,6,14/02/2018 10:53:28,5095331,3,1,0,0,0,0,...,0,20,0.0,0.0,0,0,0.0,0.000000,0,0
1048573,80,6,14/02/2018 10:53:28,5235511,3,1,0,0,0,0,...,0,20,0.0,0.0,0,0,0.0,0.000000,0,0
1048574,443,6,14/02/2018 10:53:28,5807256,6,4,327,145,245,0,...,3,20,291569.0,0.0,291569,291569,5515650.0,0.000000,5515650,5515650

In [11]:
df.to_csv("X_testpred1.csv", index=False)